# core-rs/crates/mqk-testkit/Cargo.toml
[package]
name = "mqk-testkit"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
sqlx.workspace = true

csv = "1"
tempfile = "3"

mqk-schemas = { path = "../mqk-schemas" }
mqk-artifacts = { path = "../mqk-artifacts" }
mqk-db = { path = "../mqk-db" }

[dev-dependencies]
tokio.workspace = true
